aws-samples/bedrock-engineer

- README-ja.md
- README.md
> Add APT link and star link

- package-lock.json
- src/main/api/bedrock/client.ts
- src/main/api/bedrock/types.ts
- src/main/api/bedrock/utils/awsUtils.ts
- src/renderer/src/contexts/SettingsContext.tsx
- src/renderer/src/pages/SettingPage/SettingPage.tsx
- src/renderer/src/pages/SettingPage/components/sections/AWSSection.tsx
None
Added support for an AWS session token parameter in the settings configuration.
> Add support for AWS session token in settings.

- README-ja.md
- README.md
- package.json
> v1.3.1 release

- src/main/index.ts
- src/renderer/src/i18n/locales/chat/messages.ts
- src/renderer/src/pages/ChatPage/ChatPage.tsx
- src/renderer/src/pages/ChatPage/components/InputForm/index.tsx
- src/renderer/src/pages/ChatPage/hooks/useAgentChat.ts
This Pull Request adds a folder creation feature to the folder selection dialog, allowing users to create new folders directly within the dialog interface without having to switch to another application.
> Added the functionality to create folders in the folder selection dialog / Abort Button

- README-ja.md
- README.md
- package.json
- src/renderer/src/i18n/locales/chat/index.ts
- src/renderer/src/pages/ChatPage/modals/useIgnoreFileModal.tsx
> Fix: [BUG] Ignore Files モーダルの文字列が入力できない #41

- README-ja.md
- README.md
- package.json
- src/main/api/bedrock/services/converseService.ts
- src/preload/tools/tools.ts
Amazon Nova モデルにおいて ToolUse の出力が安定しない問題を修正しました
> fix: ToolUse with Nova

- README-ja.md
- README.md
- package-lock.json
- package.json
- src/renderer/src/i18n/locales/settings/tokenAnalytics.ts
- src/renderer/src/pages/ChatPage/modals/useAgentSettingsModal.tsx
- src/renderer/src/pages/ChatPage/modals/useTokenAnalyticsModal.tsx
> デフォルトのエージェントを複製すると削除できない問題を修正

- src/main/api/bedrock/services/modelService.ts
- src/main/api/bedrock/types.ts
- src/renderer/src/i18n/config.ts
- src/renderer/src/pages/ChatPage/components/MetadataViewer/MetadataViewer.tsx
- src/renderer/src/pages/ChatPage/components/MetadataViewer/StructuredJsonView.tsx
- src/renderer/src/pages/ChatPage/components/ThinkingModeSelector/index.tsx
- src/renderer/src/pages/ChatPage/modals/useToolSettingModal/BedrockAgentSettingForm.tsx
- src/renderer/src/pages/ChatPage/modals/useToolSettingModal/CommandForm.tsx
- src/renderer/src/pages/ChatPage/modals/useToolSettingModal/KnowledgeBaseSettingForm.tsx
- src/renderer/src/pages/ChatPage/modals/useToolSettingModal/TavilySearchSettingForm.tsx
- src/renderer/src/pages/ChatPage/modals/useToolSettingModal/index.tsx
- [モデルのキャッシュのロジック](https://github.com/aws-samples/bedrock-engineer/blob/main/src/main/api/bedrock/services/modelService.ts)のバグ修正
- Bedrock Runtime API の typing の修正
- 言語設定が再起動時に適用されない問題の修正
- ダークモード利用時の表示色の修正
> fix: Bug fixes (model cache, typing, language setting, dark mode UI)

- package-lock.json
- src/renderer/src/lib/promptCacheUtils.ts
- src/renderer/src/pages/ChatPage/components/MessageList/Message.tsx
- src/renderer/src/pages/ChatPage/hooks/useAgentChat.ts
- Amazon Nova の Prompt caching にユーザーメッセージを追加
- キャッシュヒット率の計算ロジックを修正
> Fix prompt caching for Amazon Nova

- src/main/api/bedrock/services/agentService.ts
> fix: agentService client

- README-ja.md
- README.md
- package-lock.json
- package.json
> v1.9.0-release

- src/main/api/bedrock/models.ts
- src/main/api/bedrock/services/converseService.ts
Amazon Nova Premier: Our most capable model for complex tasks and teacher for model distillation
https://aws.amazon.com/jp/blogs/aws/amazon-nova-premier-our-most-capable-model-for-complex-tasks-and-teacher-for-model-distillation/
Docs
https://docs.aws.amazon.com/nova/latest/userguide/what-is-nova.html
> Nova Premier

- src/preload/store.ts
- src/renderer/src/contexts/SettingsContext.tsx
- src/renderer/src/i18n/locales/en.ts
- src/renderer/src/i18n/locales/ja.ts
- src/renderer/src/i18n/locales/planActMode.ts
- src/renderer/src/pages/ChatPage/components/AgentForm/AgentForm.tsx
- src/renderer/src/pages/ChatPage/components/AgentForm/components/AgentFormContent.tsx
- src/renderer/src/pages/ChatPage/components/AgentForm/components/AgentFormSidebar.tsx
- src/renderer/src/pages/ChatPage/components/AgentForm/components/FormActionButtons.tsx
- src/renderer/src/pages/ChatPage/components/AgentList/AgentCard.tsx
- src/renderer/src/pages/ChatPage/components/InputForm/PlanActToggle.tsx
- src/renderer/src/pages/ChatPage/components/InputForm/TextArea.tsx
- src/renderer/src/pages/ChatPage/hooks/useAgentChat.ts
- src/renderer/src/pages/ChatPage/hooks/useAgentTools.ts
- src/renderer/src/pages/ChatPage/modals/useAgentSettingsModal.tsx
- src/renderer/src/pages/ChatPage/modals/useTokenAnalyticsModal.tsx
- src/renderer/src/pages/ChatPage/modals/useToolSettingModal/index.tsx
このPull Requestは、AIアシスタントの操作モードを「Plan（計画）」と「Act（実行）」の2つに分けることで、AIの行動範囲をより細かく制御できるようにする機能を実装します。
- **Plan モード**: 読み取り専用のツールのみを有効化し、AIがファイルやデータを読み取って計画を立てることができますが、変更を加えることはできません
- **Act モード**: すべてのツール（ファイル作成・編集、コマンド実行など）を有効化し、AIが実際に変更を加えることができます
- Plan/Actモードを切り替えるトグルボタンの追加（テキストエリアの右下に配置）
- キーボードショートカット（Cmd+Shift+A または Ctrl+Shift+A）でのモード切り替え
- モード切り替え時の通知表示
- 有効なツールをモードに応じてフィルタリングする仕組み
- 読み取り専用ツールのリスト定義（readFiles, listFiles, tavilySearch, fetchWebsite, recognizeImage, retrieve, invokeBedrockAgent, think）
- 設定データの永続化（electronStoreに保存）
- 新規設定のContextへの追加（planMode, setPlanMode）
- 多言語対応（英語・日本語）
- グローバルなキーボードショートカットの実装
- PlanActToggleコンポーネントの新規作成
- ツールフィルタリングのためのuseAgentToolsフックの新規作成
- ダークモードのコントラスト改善と視認性向上
- グラフや表示要素のダークモードでの見た目改善
- トークン分析モーダルやツール設定モーダルのスタイリング強化
- …
> Plan, Act mode

- src/renderer/src/pages/ChatPage/hooks/useAgentTools.ts
- src/renderer/src/pages/ChatPage/modals/useToolSettingModal/PlanModeCompatibilityBadge.tsx
- src/renderer/src/pages/ChatPage/modals/useToolSettingModal/index.tsx
- src/types/plan-mode-tools.ts
> Add tool descripton for plan/act modde

- README-ja.md
- README.md
- package.json
> release-v1.11.0

- src/renderer/src/lib/pricing/modelPricing.test.ts
- src/renderer/src/lib/pricing/modelPricing.ts
> Model Price Claude 4

- README-ja.md
- README.md
- package-lock.json
- package.json
> release-v1.12.0

- electron-builder.yml
- src/main/handlers/camera-handlers.ts
- src/main/index.ts
- src/preload/api.ts
- src/preload/tools/handlers/system/CameraCaptureTool.ts
- src/preload/tools/handlers/system/index.ts
- src/preload/tools/registry.ts
- src/renderer/camera-preview.html
- src/renderer/src/contexts/SettingsContext.tsx
- src/renderer/src/i18n/locales/en.ts
- src/renderer/src/i18n/locales/ja.ts
- src/renderer/src/lib/camera-utils.ts
- src/renderer/src/pages/ChatPage/components/AgentForm/ToolsSection/utils/toolCategories.ts
- src/renderer/src/pages/ChatPage/components/CodeBlocks/CameraCapture/CameraCaptureResult.tsx
- src/renderer/src/pages/ChatPage/components/CodeBlocks/CameraCapture/index.ts
- src/renderer/src/pages/ChatPage/components/CodeBlocks/JSONCodeBlock.tsx
- src/renderer/src/pages/ChatPage/components/Tool/ToolIcons.tsx
- src/renderer/src/pages/ChatPage/modals/useToolSettingModal/CameraCaptureSettingForm.tsx
- src/renderer/src/pages/ChatPage/modals/useToolSettingModal/index.tsx
- src/renderer/src/pages/ChatPage/utils/placeholder.ts
- src/types/agent-chat.ts
- src/types/ipc.ts
- src/types/tools.ts
エージェント用のカメラ撮影ツール（Camera Capture Tool）を実装しました。このツールにより、以下の機能が提供されます：
- Webカメラからの画像撮影と保存
- 撮影画像のAI解析（オプション）
- エージェントごとのカメラアクセス制御
-  クラスの実装（HTML5 getUserMedia API使用）
- カメラ画像処理用のメインプロセスハンドラの追加
- カメラ撮影結果を表示するUIコンポーネント
- カメラアクセス設定UIの追加
- ツールセレクションへのカメラツールの追加
- HTML5 getUserMedia APIによるカメラアクセス
- エージェントごとのカメラ許可設定
- 画像キャプチャ結果のAI解析統合
- カメラアクセスに関するエラーハンドリング
この実装により、AIエージェントがカメラ機能を活用したビジュアルタスクを実行できるようになります。
> カメラ撮影機能の実装（Camera Capture Tool）

- src/preload/tools/handlers/thinking/ThinkTool.ts
- src/renderer/src/i18n/locales/chat/tools.ts
- src/renderer/src/i18n/locales/thinkingMode.ts
- src/renderer/src/pages/SettingPage/components/ThinkingModeSettings.tsx
> Improving the accuracy of think tools

- src/renderer/src/i18n/locales/settings/agentToolsSettings.ts
- src/renderer/src/pages/ChatPage/components/AgentForm/AgentForm.tsx
- src/renderer/src/pages/ChatPage/components/AgentForm/BasicSection.tsx
- src/renderer/src/pages/ChatPage/components/AgentForm/McpServerSection/McpServerList.tsx
- src/renderer/src/pages/ChatPage/components/AgentForm/McpServerSection/ServerListItem.tsx
- src/renderer/src/pages/ChatPage/components/AgentForm/McpServerSection/index.tsx
- src/renderer/src/pages/ChatPage/components/AgentForm/SystemPromptSection.tsx
- src/renderer/src/pages/ChatPage/components/AgentForm/ToolsSection/components/AvailableToolsTab/ToolCategorySection.tsx
- src/renderer/src/pages/ChatPage/components/AgentForm/ToolsSection/components/AvailableToolsTab/ToolItem.tsx
- src/renderer/src/pages/ChatPage/components/AgentForm/components/AgentFormContent.tsx
- src/renderer/src/pages/ChatPage/components/AgentForm/components/AgentFormSidebar.tsx
- src/renderer/src/pages/ChatPage/components/AgentForm/components/FormActionButtons.tsx
- src/renderer/src/pages/ChatPage/components/AgentList/AgentList.tsx
- src/renderer/src/pages/ChatPage/modals/useAgentSettingsModal.tsx
- src/renderer/src/pages/ChatPage/modals/useTokenAnalyticsModal.tsx
- src/renderer/src/pages/ChatPage/modals/useToolSettingModal/index.tsx
> improve dark mode style

- src/renderer/src/components/Markdown/styles.module.css
> darkmode table markdown ui

- src/renderer/src/lib/drawio/xmlParser.ts
- src/renderer/src/pages/ChatPage/components/AgentList/useAgentFilter.ts
- src/renderer/src/pages/ChatPage/components/Code/CodeRenderer.tsx
- src/renderer/src/pages/ChatPage/components/Code/DrawIOBlock.tsx
- src/renderer/src/pages/ChatPage/components/Code/ResizableContainer.tsx
- src/renderer/src/pages/ChatPage/constants/AGENTS_ENVIRONMENT_CONTEXT.ts
- src/renderer/src/pages/ChatPage/constants/DEFAULT_AGENTS.ts
- src/renderer/src/pages/DiagramGeneratorPage/DiagramGeneratorPage.tsx
> Diagram Viewer in chat

- package-lock.json
- src/main/api/command/commandService.ts
- src/preload/store.ts
- src/renderer/src/i18n/locales/settings/agentToolsSettings.ts
- src/renderer/src/pages/ChatPage/modals/useToolSettingModal/CommandForm.tsx
Windows環境で`aws s3 ls`などのコマンド実行時に発生していた「PID is undefined」および「The system cannot find the path specified」エラーを修正しました。
Fixed "PID is undefined" and "The system cannot find the path specified" errors when executing commands like `aws s3 ls` on Windows environment.
1. **PID未定義エラー**: `Failed to start process: PID is undefined`
2. **パス指定エラー**: `The system cannot find the path specified`
3. **変数名衝突**: `Cannot access 'process2' before initialization`
4. **環境変数継承問題**: ElectronアプリでのPATH設定不備
1. **PID undefined error**: `Failed to start process: PID is undefined`
2. **Path specification error**: `The system cannot find the path specified`
3. **Variable name collision**: `Cannot access 'process2' before initialization`
4. **Environment variable inheritance**: PATH configuration issues in Electron apps
- …
> fix: Windows environment command execution PID is undefined error

- src/common/agents/toolDescriptionProvider.ts
- src/common/agents/toolRuleGenerator.ts
- src/common/utils/placeholderUtils.ts
- src/main/api/bedrock/services/backgroundAgent/BackgroundAgentService.ts
- src/main/api/bedrock/services/backgroundAgent/MainToolDescriptionProvider.ts
- src/main/api/bedrock/services/backgroundAgent/MainToolSpecProvider.ts
- src/preload/index.ts
- src/preload/tools/handlers/command/ExecuteCommandTool.ts
- src/renderer/src/contexts/SettingsContext.tsx
- src/renderer/src/pages/ChatPage/components/AgentForm/SystemPromptSection.tsx
- src/renderer/src/pages/ChatPage/components/ExampleScenarios/index.tsx
- src/renderer/src/pages/ChatPage/constants/AGENTS_ENVIRONMENT_CONTEXT.ts
*Issue*
Background Agent において SystemPrompt を組み立てるロジックにおいて通常の Agent Chat と一部乖離があったため、コマンド実行が安定しない不具合がありました。
> refactor: SystemPrompt Builder

- src/common/agents/toolRuleGenerator.ts
- src/renderer/src/contexts/SettingsContext.tsx
> Improve plan act mode

- .github/workflows/draft-release.yml
- package-lock.json
- package.json
- src/main/handlers/docx-handlers.ts
- src/main/index.ts
- src/preload/lib/DocxReader.ts
- src/preload/tools/handlers/filesystem/ReadFilesTool.ts
- src/types/ipc.ts
> DocxReader

- .github/workflows/draft-release.yml
- package-lock.json
- package.json
- src/main/handlers/docx-handlers.ts
- src/main/index.ts
- src/preload/lib/DocxReader.ts
- src/preload/tools/handlers/command/ExecuteCommandTool.ts
- src/preload/tools/handlers/filesystem/ReadFilesTool.ts
- src/renderer/src/contexts/SettingsContext.tsx
- src/types/ipc.ts
> Fixed whitelist function of executeCommand tool in BackgroundAgentService

- src/preload/tools/handlers/web/TavilySearchTool.ts
- src/renderer/src/contexts/SettingsContext.tsx
- src/renderer/src/i18n/locales/en.ts
- src/renderer/src/i18n/locales/ja.ts
- src/renderer/src/pages/ChatPage/modals/useToolSettingModal/TavilySearchSettingForm.tsx
- src/renderer/src/pages/ChatPage/modals/useToolSettingModal/index.tsx
- src/types/agent-chat.ts
> TavilySearch Tool Domain Filtering
